### ISSUE TITLE
Full cache reload after 3.5.0 crashes

### ISSUE THREAD

**Issue by JRDetwiler** [OxygenCobalt/Auxio#810]
It tried to fully reload my library and I got
```
java.lang.Exception: DeviceLibrary creation failed: java.lang.IllegalArgumentException: Comparison method violates its general contract!
	at org.oxycblt.auxio.music.MusicRepositoryImpl$indexImpl$deviceLibraryJob$1.invokeSuspend(SourceFile:92)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:8)
	at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Unknown Source:6)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(SourceFile:23)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:31)
	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:94)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(SourceFile:92)
```

**Comment by denny466** [comment]
Hi! I'm getting the same error & log after updating 3.4.3 to 3.5.0. Rolled back to 3.4.3 and all 15680 songs loaded successfully. Can you reproduce @OxygenCobalt or do i offer some samples?

**Comment by OxygenCobalt** [comment]
Please use this debug APK and report the updated stack trace @denny466 @JRDetwiler, I need it to determine the exact location of the error

[Auxio_Canary.zip](https://github.com/user-attachments/files/15993432/Auxio_Canary.zip)

**Comment by denny466** [comment]
@OxygenCobalt Music loading failed

java.lang.Exception: DeviceLibrary creation failed: java.lang.IllegalArgumentException: Comparison method violates its general contract!
	at org.oxycblt.auxio.music.MusicRepositoryImpl$indexImpl$deviceLibraryJob$1.invokeSuspend(MusicRepository.kt:473)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:32)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)

**Comment by OxygenCobalt** [comment]
Okay, that turned out not to be enough. I need to do another patch that provides finer detail stack traces, will try to do that later this evening @denny466.

**Comment by OxygenCobalt** [comment]
Can you guys get the stack trace from this build @denny466 @JRDetwile?

[Auxio_Canary.zip](https://github.com/user-attachments/files/16038732/Auxio_Canary.zip)

**Comment by denny466** [comment]
@OxygenCobalt 
```kotlin
java.lang.Exception: DeviceLibrary creation failed: java.lang.IllegalArgumentException: Comparison method violates its general contract!
	at java.util.TimSort.mergeHi(TimSort.java:903)
	at java.util.TimSort.mergeAt(TimSort.java:520)
	at java.util.TimSort.mergeCollapse(TimSort.java:448)
	at java.util.TimSort.sort(TimSort.java:245)
	at java.util.Arrays.sort(Arrays.java:1344)
	at java.util.ArrayList.sort(ArrayList.java:1738)
	at java.util.Collections.sort(Collections.java:210)
	at kotlin.collections.CollectionsKt__MutableCollectionsJVMKt.sortWith(MutableCollectionsJVM.kt:42)
	at org.oxycblt.auxio.list.sort.Sort.songsInPlace(Sort.kt:105)
	at org.oxycblt.auxio.list.sort.Sort.songs(Sort.kt:51)
	at org.oxycblt.auxio.image.extractor.Cover$Companion.order(Cover.kt:51)
	at org.oxycblt.auxio.image.extractor.ParentCover$Companion.from(Cover.kt:64)
	at org.oxycblt.auxio.music.device.ArtistImpl.<init>(DeviceMusicImpl.kt:479)
	at org.oxycblt.auxio.music.device.DeviceLibraryFactoryImpl.create(DeviceLibrary.kt:261)
	at org.oxycblt.auxio.music.device.DeviceLibraryFactoryImpl$create$1.invokeSuspend(Unknown Source:18)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:32)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)

	at org.oxycblt.auxio.music.MusicRepositoryImpl$indexImpl$deviceLibraryJob$1.invokeSuspend(MusicRepository.kt:476)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:32)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)


```

**Comment by OxygenCobalt** [comment]
Cool @JRDetwiler @denny466, can you try this APK to see if it works?

[Auxio_Canary.zip](https://github.com/user-attachments/files/16042657/Auxio_Canary.zip)

More or less, I was abusing certain functionality to do sorting (in this case cover sorting) which crashed w/certain inputs. It's been in Auxio for several versions now, but since I sort album cover orderings during music loading now it was finally triggered on your end. I got rid of that stuff and it should work now, hopefully.

**Comment by denny466** [comment]
@OxygenCobalt It works. Thanks! 🫶
The first scan took 7 minutes and when I start the app after fully closing it, it loads 20 seconds. 3.4.3 is several times faster but I guess this is discardable since not everybody has a 5 figure library. Maybe caching would be a idea? I'll be back when something else comes up. Best regards!

**Comment by OxygenCobalt** [comment]
> The first scan took 7 minutes and when I start the app after fully closing it, it loads 20 seconds. 3.4.3 is several times faster but I guess this is discardable since not everybody has a 5 figure library. Maybe caching would be a idea? I'll be back when something else comes up. Best regards!

It's a debug build, so it's going to be a *lot* slower. The 3.5.1 patch will be much faster.

Anyway, thanks, will close this now.

**Comment by denny466** [comment]
Hey @OxygenCobalt I'm afraid the issue came back to haunt me on 3.5.1

``` kotlin 
java.lang.Exception: DeviceLibrary creation failed: java.lang.IllegalArgumentException: Comparison method violates its general contract!
	at java.util.TimSort.mergeHi(TimSort.java:903)
	at java.util.TimSort.mergeAt(TimSort.java:520)
	at java.util.TimSort.mergeForceCollapse(TimSort.java:461)
	at java.util.TimSort.sort(TimSort.java:254)
	at java.util.Arrays.sort(Arrays.java:1344)
	at java.util.ArrayList.sort(ArrayList.java:1738)
	at java.util.Collections.sort(Collections.java:210)
	at kotlin.collections.CollectionsKt__MutableCollectionsJVMKt.sortWith(Unknown Source:12)
	at org.oxycblt.auxio.list.sort.Sort$Mode$ByAlbum.sortSongs(SourceFile:76)
	at org.oxycblt.auxio.list.sort.Sort.songs(SourceFile:14)
	at org.oxycblt.auxio.image.extractor.Cover$Companion.order(SourceFile:8)
	at org.oxycblt.auxio.music.device.ArtistImpl.<init>(SourceFile:381)
	at okio.Path$Companion.create(SourceFile:13)
	at org.oxycblt.auxio.music.device.DeviceLibraryFactoryImpl$create$1.invokeSuspend(Unknown Source:16)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:8)
	at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Unknown Source:6)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(SourceFile:23)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:31)
	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:94)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(SourceFile:92)

	at org.oxycblt.auxio.music.MusicRepositoryImpl$indexImpl$deviceLibraryJob$1.invokeSuspend(SourceFile:88)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:8)
	at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Unknown Source:6)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(SourceFile:23)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:31)
	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:94)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(SourceFile:92)
```

**Comment by OxygenCobalt** [comment]
The fix apparently made the bug worse. I absolutely hate this OS.

Report the error from this @denny466 @JRDetwiler 

[Auxio_SortTrace.zip](https://github.com/user-attachments/files/16152539/Auxio_SortTrace.zip)

**Comment by denny466** [comment]
Here you go @OxygenCobalt 

``` kotlin 
java.lang.Exception: DeviceLibrary creation failed: java.lang.Exception: Album asc sort error: java.lang.IllegalArgumentException: Comparison method violates its general contract!
	at org.oxycblt.auxio.list.sort.Sort$Mode$ByAlbum.sortSongs(SourceFile:148)
	at org.oxycblt.auxio.list.sort.Sort.songs(SourceFile:14)
	at org.oxycblt.auxio.image.extractor.Cover$Companion.order(SourceFile:8)
	at org.oxycblt.auxio.music.device.ArtistImpl.<init>(SourceFile:381)
	at okio.Path$Companion.create(SourceFile:13)
	at org.oxycblt.auxio.music.device.DeviceLibraryFactoryImpl$create$1.invokeSuspend(Unknown Source:16)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:8)
	at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Unknown Source:6)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(SourceFile:23)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:31)
	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:94)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(SourceFile:92)

	at org.oxycblt.auxio.music.MusicRepositoryImpl$indexImpl$deviceLibraryJob$1.invokeSuspend(SourceFile:88)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:8)
	at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Unknown Source:6)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(SourceFile:23)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:31)
	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:94)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(SourceFile:92)
```

**Comment by OxygenCobalt** [comment]
Alright, so it's an issue with name comparison. Can you see if disabling Settings -> Content -> Intelligent sorting does anything @denny466?

**Comment by denny466** [comment]
Disabling Intelligent sorting did the trick on both the APK you provided and F-droid release. Listing to music just fine now. Thanks @OxygenCobalt

**Comment by OxygenCobalt** [comment]
Can you try out this new APK really quick (clear storage so you were in the same situation when you reported the bug) @denny466 

[Auxio_Sort2.zip](https://github.com/user-attachments/files/16154261/Auxio_Sort2.zip)

**Comment by denny466** [comment]
This APK successfully loaded my library with intelligent sorting enabled! Nice going @OxygenCobalt

**Comment by OxygenCobalt** [comment]
Thanks pushed 3.5.2 @denny466

**Comment by JRDetwiler** [comment]
So sorry I haven't been able to test until now, the latest fix works for me too. Thank you so much!
